# Environment Settings
url=https://demoqa.com/automation-practice-form
browser=chrome
timeout=20

# Test Data Settings
excelPath=src/main/resources/testdata/TestData.xlsx
# Headless Flag
headless=false